//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Users = new HashSet<User>();
        }
       [Display(Name ="ID")]
        public int EmployeeId { get; set; }

        [Required(ErrorMessage ="Name Required")]
        [Display(Name ="Employee Name")]
        public string EmployeeName { get; set; }
        [Required(ErrorMessage ="Email Required")]
        [Display(Name ="Email Address")]
        public string Email { get; set; }
        [Required(ErrorMessage ="Phone no Required")]
        [Display(Name ="Phone Number")]
        public string CellNo { get; set; }
        [Required(ErrorMessage ="Address Requred")]
        [Display(Name ="Address")]
        public string Address { get; set; }
        [Required(ErrorMessage ="Salary Requred")]
        [Display(Name ="Salary")]
        public Nullable<decimal> Salary { get; set; }
        [Required]
        [Display(Name ="Added By")]
        public string AddedBy { get; set; }
        [Required(ErrorMessage = "Status Requred")]
        [Display(Name = "Status")]
        public string IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
